### ISSUE TITLE
Trouble with FillRule::NonZero and Solidity

### ISSUE THREAD

**Issue by phlay** [femtovg/femtovg#124] opened 2022-11-04 14:55 UTC
The [Solidity](https://docs.rs/femtovg/latest/femtovg/enum.Solidity.html) feature re-orientates the user supplied winding direction of a given path. This might be useful in some cases, but in others this could be a problem: For example i'm drawing externally generated SVG files that make heavy use of the [nonzero fillrule](https://en.wikipedia.org/wiki/Nonzero-rule)  to create polygons with "holes". Without the Solidity feature the polygons would show up correctly, but femtovg [reverses](https://github.com/femtovg/femtovg/blob/v0.3.7/src/path/cache.rs#L238-L247) the winding direction of the given paths and in doing so corrupting the nonzero fillrule semantic.

Of course one could try to detect the winding direction and manually set the solidity to Solid or Hole to counteract femtovg's reversing, but this would be cumbersome and inefficient. I would much rather prefer to have something like Solidity::Natural that instructs femtovg to not touch the supplied path and use it as is (or make solidity optional, like my proposal below).

Here is a small example to reproduce the problem:
```
let paint = Paint::color(Color::rgb(255, 255, 255))
    .with_fill_rule(FillRule::NonZero);

let mut path = Path::new();
path.move_to(300., 100.);
path.line_to(100., 100.);
path.line_to(100., 300.);
path.line_to(300., 300.);
path.close();

path.move_to(150., 150.);
path.line_to(250., 150.);
path.line_to(250., 250.);
path.line_to(150., 250.);
path.close();

canvas.fill_path(&mut path, &paint);
```
This should draw a white square with a square hole in it, but does not. Of course here `path.solidity(Solidity::Hole)` would make it work, but this is not well suited for more complex cases where the winding direction is already defining what is inside the polygon and what not.

I'm sure there are multiple ways to fix this, but something like that should work: Make solidity field in Contour an `Option<Solidity>` instead of just `Solidity` (with default None) and in `PathCache::new`:
```           
// Enforce solidity by reversing the winding, if the user wishes for it
if let Some(solidity) = contour.solidity {
    let area = Contour::polygon_area(points);

    if solidity == Solidity::Solid && area < 0.0 {
        points.reverse();
    }

    if solidity == Solidity::Hole && area > 0.0 {
        points.reverse();
    }
}
```

**Comment by phlay** [comment] 2022-11-04 15:55
Have a look at PR #125 illustrating my proposal

**Comment by mhfan** [comment] 2024-05-22 09:17
I recently encountered a similar problem and it took me a long time to locate the cause.

Why hasn't this patch been merged yet?

**Comment by tronical** [comment] 2024-05-22 14:00
That's a good question... somehow I lost track of this one, but it makes a lot of sense (despite being a breaking change).

**Comment by tronical** [comment] 2024-05-22 14:20
@adamnemecek @peterprototypes What do you think?

**Comment by adamnemecek** [comment] 2024-05-22 17:14
Seems reasonable.

**Comment by peterprototypes** [comment] 2024-05-22 17:29
Agreed, we can merge this

**Comment by mhfan** [comment] 2024-05-23 02:54
There seems to be another issue here.

Please check the two screenshots below. The first one is the result of applying this patch on the master branch, and the second one is the result based on the latest code of the master branch.

You can see that each glyph in the previous screenshot seems to be "fatter" than normal. I can't figure out why, the difference is just this patch. Anyone can shed some light?

Note: The glyphs shown in the figure are drawn by calling `fill_path` with the path of glyphs, not by `fill_text`.

<img width="204" alt="image" src="https://github.com/femtovg/femtovg/assets/1171428/4daf24a4-3cbc-49e3-9f70-96eac1c36481">
<img width="204" alt="image" src="https://github.com/femtovg/femtovg/assets/1171428/382f54e4-bcc2-4b55-b84f-0639e9ad25d1">

**Comment by mhfan** [comment] 2024-05-28 08:54
Hello, anyone can check this?

**Comment by mhfan** [comment] 2024-06-18 06:31
When `woff` set to `0.0`, the extended rendering issue caused by this patch seems to have been resolved. 

https://github.com/femtovg/femtovg/blob/4e40a61f824a8ea1bd361b4d227a2187e912124a/src/path/cache.rs#L549-L551

<img width="209" alt="image" src="https://github.com/femtovg/femtovg/assets/1171428/9ca3e099-1062-4b41-a0e6-507fddb9a511">

However, after careful comparison, I found that Femtovg's rendering (even without this patch) is still one or two pixels fatter. As shown in the figure below, which is [Ghostscript_Tiger.svg](https://github.com/femtovg/femtovg/blob/master/examples/assets/Ghostscript_Tiger.svg) rendered with Femtovg and Chrome respectively, take a closer look at the thickness of the tiger's each whisker respectively.

<img width="1007" alt="image" src="https://github.com/femtovg/femtovg/assets/1171428/8ec513e9-511f-47a1-bb78-74bd17d9cb0c">

In addition, the color of Femtovg's rendering seems to be more vivid than Chrome, and I am also curious about how it is done.

**Comment by peterprototypes** [comment] 2024-06-18 08:30
Hi @mhfan. The algo in femtovg is taken from https://github.com/memononen/nanovg 

After your comments I took a closer look to try to remember what was what and I think there may be a mistake between the original and femtovg. In the [original implementation](https://github.com/memononen/nanovg/blob/f93799c078fa11ed61c078c65a53914c8782c00b/src/nanovg.c#L1929) the parameters `lw` and `lu` are initialized to fringe width +/- woff, [while in femtovg](https://github.com/femtovg/femtovg/blob/4e40a61f824a8ea1bd361b4d227a2187e912124a/src/path/cache.rs#L586) they are set to lw = fringe_width + woff and lu to 0.0

Maybe it's worth the try to test what will happen if we do it like the original.

**Comment by mhfan** [comment] 2024-06-19 08:16
The femtovg implementation seems exact as the original. And there are [many similar related issues](https://github.com/memononen/nanovg/issues/571) found in nanovg project.

Specially, [nanovgXC](https://github.com/styluslabs/nanovgXC.git) claimed to solve these issues, any chance to integrate the fixes?

**Closed** 2024-06-27 16:32 UTC
